eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registration:8761/eureka/
  instance:
#     prefer-ip-address: true
#     ip-address: http://eureka-server:8761/eureka/
    hostname: service-registration
